[Linux] Can't run artifact build against current m-c because it try to run 'hg' in my objdir, which then complains there is no repository there
gijs@linux-vm:~/mozilla-central$ ./mach build
0:00.09 /usr/bin/make -f client.mk -s
0:00.55 Adding client.mk option from /home/gijs/mozilla-central/.mozconfig:
0:00.55 MOZ_OBJDIR=/home/gijs/mc-artifact
0:00.55 OBJDIR=/home/gijs/mc-artifact
0:00.55 FOUND_MOZCONFIG=/home/gijs/mozilla-central/.mozconfig
0:01.11 abort: no repository found in '/home/gijs/mc-artifact' (.hg not found)!
0:01.13 Error running mach:
0:01.13
0:01.13 ['--log-no-times', 'artifact', 'install']
0:01.13
0:01.13 The error occurred in code that wa called by the mach command. This is either
0:01.13 a bug in the called code itself or in the way that mach is calling it.
0:01.13
0:01.13 You should consider filing a bug for this issue.
0:01.13
0:01.13 If filing a bug, please include the full output of mach, including this error
0:01.13 message.
0:01.13
0:01.13 The detail of the failure are a follows:
0:01.13
0:01.13 CalledProcessError: Command '[u'/usr/local/bin/hg', u'log', u'--template', u'{node}\n', u'-r', u'last(public() and ::., 500)']' returned non-zero exit status 255
0:01.13
0:01.13 File "/home/gijs/mozilla-central/python/mozbuild/mozbuild/mach_commands.py", line 1506, in artifact_install
0:01.13 return artifacts.install_from(source, self.distdir)
0:01.13 File "/home/gijs/mozilla-central/python/mozbuild/mozbuild/artifacts.py", line 1034, in install_from
0:01.13 return self.install_from_recent(distdir)
0:01.13 File "/home/gijs/mozilla-central/python/mozbuild/mozbuild/artifacts.py", line 997, in install_from_recent
0:01.13 return self._install_from_hg_pushheads(hg_pushheads, distdir)
0:01.13 File "/home/gijs/mozilla-central/python/mozbuild/mozbuild/artifacts.py", line 977, in _install_from_hg_pushheads
0:01.13 for hg_hash in hg_pushheads:
0:01.13 File "/home/gijs/mozilla-central/python/mozbuild/mozbuild/artifacts.py", line 871, in _find_pushheads
0:01.13 last_revs = self._get_recent_public_revisions()
0:01.13 File "/home/gijs/mozilla-central/python/mozbuild/mozbuild/artifacts.py", line 863, in _get_recent_public_revisions
0:01.13 num=NUM_REVISIONS_TO_QUERY)
0:01.13 File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
0:01.13 raise CalledProcessError(retcode, cmd, output=output)
0:01.16 Makefile:249: recipe for target 'recurse_artifact' failed
0:01.16 make[4]: *** [recurse_artifact] Error 1
0:01.16 /home/gijs/mozilla-central/config/recurse.mk:32: recipe for target 'artifact' failed
0:01.16 make[3]: *** [artifact] Error 2
0:01.16 /home/gijs/mozilla-central/config/rules.mk:540: recipe for target 'default' failed
0:01.16 make[2]: *** [default] Error 2
0:01.16 /home/gijs/mozilla-central/client.mk:413: recipe for target 'realbuild' failed
0:01.16 make[1]: *** [realbuild] Error 2
0:01.16 client.mk:168: recipe for target 'build' failed
0:01.16 make: *** [build] Error 2
0:01.16 0 compiler warning present.
