Intermittent b2g test_framebindings-04.js | Process still running after test!
https://tbpl.mozilla.org/php/getParsedLog.php?id=21456404&tree=Mozilla-Inbound
b2g_ics_armv7a_gecko_emulator_vm mozilla-inbound opt test xpcshell on 2013-04-04 12:29:49 PDT for push b5f2678e1cc8
slave: tst-linux64-ec2-046

19:46:32 INFO - TEST-INFO | /builds/slave/test/build/tests/xpcshell/tests/toolkit/devtools/debugger/tests/unit/test_framebindings-04.js | running test ...
19:51:32 WARNING - TEST-UNEXPECTED-FAIL | /builds/slave/test/build/tests/xpcshell/tests/toolkit/devtools/debugger/tests/unit/test_framebindings-04.js | test failed (with xpcshell return code: -1), see following log:
19:51:32 INFO - >>>>>>>
19:51:32 INFO - Traceback (most recent call last):
19:51:32 INFO - File "runtestsb2g.py", line 64, in launchProcess
19:51:32 INFO - outputFile = XPCShellRemote.launchProcess(self, cmd, stdout, stderr, env, cwd)
19:51:32 INFO - File "/builds/slave/test/build/tests/xpcshell/remotexpcshelltests.py", line 280, in launchProcess
19:51:32 INFO - self.shellReturnCode = self.device.shell(cmd, f)
19:51:32 INFO - File "/builds/slave/test/build/venv/local/lib/python2.7/site-packages/mozdevice/devicemanagerADB.py", line 138, in shell
19:51:32 INFO - raise DMError("Timeout exceeded for shell call")
19:51:32 INFO - DMError: Timeout exceeded for shell call
19:51:32 INFO - <<<<<<<
19:51:33 WARNING - TEST-UNEXPECTED-FAIL | /builds/slave/test/build/tests/xpcshell/tests/toolkit/devtools/debugger/tests/unit/test_framebindings-04.js | Process still running after test!
19:51:33 INFO - >>>>>>>
19:51:33 INFO - Traceback (most recent call last):
19:51:33 INFO - File "runtestsb2g.py", line 64, in launchProcess
19:51:33 INFO - outputFile = XPCShellRemote.launchProcess(self, cmd, stdout, stderr, env, cwd)
19:51:33 INFO - File "/builds/slave/test/build/tests/xpcshell/remotexpcshelltests.py", line 280, in launchProcess
19:51:33 INFO - self.shellReturnCode = self.device.shell(cmd, f)
19:51:33 INFO - File "/builds/slave/test/build/venv/local/lib/python2.7/site-packages/mozdevice/devicemanagerADB.py", line 138, in shell
19:51:33 INFO - raise DMError("Timeout exceeded for shell call")
19:51:33 INFO - DMError: Timeout exceeded for shell call
19:51:33 INFO - <<<<<<<
