POST failures uploading outgoing items don't log a failure reason
via TPS we are seeing logs like:

> 1463445396414	Sync.Collection	DEBUG	POST Length: 9471
> 1463445396608	Sync.Status	DEBUG	Status for engine prefs: error.engine.reason.unknown_fail
> 1463445396609	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed_partial
> 1463445396609	Sync.ErrorHandler	DEBUG	prefs failed: Error (resource://services-sync/resource.js:405:19) JS Stack trace: waitForSyncCallback@async.js:98:7 < Res__request@resource.js:398:14 < Res_post@resource.js:439:12 < newPostQueue/poster@record.js:635:14 < flush@record.js:703:23 < SyncEngine.prototype._uploadOutgoing@engines.js:1506:7 < SyncEngine.prototype._sync@engines.js:1557:7 < WrappedNotify@util.js:146:21 < Engine.prototype.sync@engines.js:670:5 < _syncEngine@enginesync.js:213:7 < sync@enginesync.js:163:15 < onNotify@service.js:1262:7 < WrappedNotify@util.js:146:21 < WrappedLock@util.js:101:16 < _lockedSync@service.js:1252:12 < sync/<@service.js:1244:14 < WrappedCatch@util.js:75:16 < sync@service.js:1232:5 < TPS__Sync@tps.jsm:926:5 < TPS.RunNextTestAction@tps.jsm:607:7 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < Res_post@resource.js:439:12 < newPostQueue/poster@record.js:635:14 < flush@record.js:703:23 < SyncEngine.prototype._uploadOutgoing@engines.js:1506:7 < SyncEngine.prototype._sync@engines.js:1557:7 < WrappedNotify@util.js:146:21 < Engine.prototype.sync@engines.js:670:5 < _syncEngine@enginesync.js:213:7 < sync@enginesync.js:163:15 < onNotify@service.js:1262:7 < WrappedNotify@util.js:146:21 < WrappedLock@util.js:101:16 < _lockedSync@service.js:1252:12 < sync/<@service.js:1244:14 < WrappedCatch@util.js:75:16 < sync@service.js:1232:5 < TPS__Sync@tps.jsm:926:5 < TPS.RunNextTestAction@tps.jsm:607:7 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5
> 1463445396610	Sync.Engine.Passwords	DEBUG	First sync, uploading all items
> 1463445396610	Sync.Engine.Passwords	INFO	0 outgoing items pre-reconciliation
> 1463445396612	Sync.BrowserIDManager	DEBUG	_ensureValidToken already has one
> 1463445396791	Sync.Status	DEBUG	Status for engine passwords: error.engine.reason.unknown_fail
> 1463445396791	Sync.Status	DEBUG	Status.service: error.sync.failed_partial => error.sync.failed_partial
> 1463445396791	Sync.ErrorHandler	DEBUG	passwords failed: Error (resource://services-sync/resource.js:405:19) JS Stack trace: waitForSyncCallback@async.js:98:7 < Res__request@resource.js:398:14 < Res_get@resource.js:425:12 < SyncEngine.prototype._processIncoming@engines.js:1135:18 < SyncEngine.prototype._sync@engines.js:1555:7 < WrappedNotify@util.js:146:21 < Engine.prototype.sync@engines.js:670:5 < _syncEngine@enginesync.js:213:7 < sync@enginesync.js:163:15 < onNotify@service.js:1262:7 < WrappedNotify@util.js:146:21 < WrappedLock@util.js:101:16 < _lockedSync@service.js:1252:12 < sync/<@service.js:1244:14 < WrappedCatch@util.js:75:16 < sync@service.js:1232:5 < TPS__Sync@tps.jsm:926:5 < TPS.RunNextTestAction@tps.jsm:607:7 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < Res_get@resource.js:425:12 < SyncEngine.prototype._processIncoming@engines.js:1135:18 < SyncEngine.prototype._sync@engines.js:1555:7 < WrappedNotify@util.js:146:21 < Engine.prototype.sync@engines.js:670:5 < _syncEngine@enginesync.js:213:7 < sync@enginesync.js:163:15 < onNotify@service.js:1262:7 < WrappedNotify@util.js:146:21 < WrappedLock@util.js:101:16 < _lockedSync@service.js:1252:12 < sync/<@service.js:1244:14 < WrappedCatch@util.js:75:16 < sync@service.js:1232:5 < TPS__Sync@tps.jsm:926:5 < TPS.RunNextTestAction@tps.jsm:607:7 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5 < TPS.RunNextTestAction@tps.jsm:633:5

From which we can deduce that a POST failed, but can't deduce why. We need to ensure the logs capture the reasons - at least for the obvious 2 of "can't connect" and "http request failed". I'm fairly sure this isn't limited to POSTs